[package]
name = "jlu-gpa-calculator-desktop"
version = "1.0.1"
description = "Windows desktop GPA calculator for Jilin University undergraduates"
authors = ["Coldymemos", "DailyPotato"]
license = "PolyForm-Noncommercial-1.0.0"
repository = "https://github.com/Coldymemos/JLU-GPA-Calculator-for-Windows-Desktop"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "jlu_gpa_calculator_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
rusqlite = { version = "0.37", features = ["backup", "bundled"] }
sha2 = "0.10"
tauri-plugin-dialog = "2"
notify = "8"
